name: ChunkWorldEditor
main: ChunkWorldEditor\ChunkWorldEditor
version: 1.0
api: 3.0.0
load: POSTWORLD
commands:
 ////set:
  description: 非同期なチャンクワールドエディタです。
  usage: "////set"
 ////setpp:
  description: チャンクワールドエディタです。
  usage: "////setpp"
 ////setppp:
  description: チャンクワールドエディタです。
  usage: "////setppp"
 ////uset:
  description: 非同期なチャンクワールドエディタです。
  usage: "////uset"
 ////usetpp:
  description: チャンクワールドエディタです。
  usage: "////usetpp"
 ////usetppp:
  description: チャンクワールドエディタです。
  usage: "////usetppp"
 ////undo:
  description: undoを実行致します。
  usage: "////undo"
 ////e:
  description: 非同期なチャンクワールドエディタ、座標リセットコマンドでございます。
  usage: "/////e"
